Here are all five tasks
js-tasks-ru/jsbasic-20210621_qb59egkw pull request #4
Opened 2021-06-25 12:59 UTC by alukard111

Perhaps there was a misunderstanding of how to solve the correct factorial with 0! But maybe this is the right decision.

There were no problems with validation, capitalization, spam and string trimming. Everything is simple so far

2021-06-25 13:00 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-25 20:54 UTC, SinimaWath requested changes

2021-06-25 20:54 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  // Возможно это хитрожопо, но чёт я не понял как иначе это запилить, если факториал === 0.
Можно добавить в самое начало функции:
```
function factorial(n) {
  if (n === 0 || n === 1) {
    return 1;
  }
}
```

2021-06-25 20:54 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (!str) {
Присваивание значений аргументам функций, это считается антипаттерном - плохим, тоном. Который может привести к неявным багам.

Лучше создать новую переменную

2021-06-25 20:54 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
можно в одну строчку

2021-06-25 20:54 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  let points = '…'
Почему let, а не const?

2021-06-25 20:54 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  } else {
Тут else немного лишний, когда у тебя есть return, то можно просто:
```
if (str.length > maxlength) {
  return `${str.slice(0, maxlength - 1)}${points}`;
}

return str;
```

2021-06-26 00:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-26 21:58 UTC, SinimaWath requested changes

2021-06-26 21:58 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    return result.toUpperCase()
А зачем тут ты делаешь toUpperCase?

2021-06-26 21:58 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return result
можно вернуть значение без временной переменной: `return result[0].toUpperCase() + result.slice(1)`

2021-06-27 13:06 UTC, alukard111 commented on 1-module/3-task/index.js
> +    return result.toUpperCase()
Да, согласен, это ни на что не влияет.
Затупил, буду внимательнее.

2021-06-27 13:06 UTC, alukard111 commented on 1-module/3-task/index.js
> +  return result
И то верно.

2021-06-27 13:07 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-27 13:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-06-27 13:16 UTC, SinimaWath approved these changes

2021-06-27 13:16 UTC, merged