This is the second module with tasks. All completed
js-tasks-ru/jsbasic-20210621_qb59egkw pull request #5
Opened 2021-06-30 22:55 UTC by alukard111

2021-06-30 22:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-01 15:27 UTC, SinimaWath requested changes

2021-07-01 15:27 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if (salaries[key] != Infinity && salaries[key] != -Infinity && salaries[key] > 0 ) {
Молодец, что сам написал.

В браузере есть метод Number.IsFinite - давай еще его используем

2021-07-01 16:12 UTC, alukard111 commented on 2-module/1-task/index.js
> +    if (salaries[key] != Infinity && salaries[key] != -Infinity && salaries[key] > 0 ) {
Да, так будет проще..

2021-07-01 16:14 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-02 13:51 UTC, SinimaWath approved these changes
все круто

2021-07-02 13:52 UTC, merged