4-module I decided
js-tasks-ru/jsbasic-20210621_qb59egkw pull request #7
Opened 2021-07-08 23:42 UTC by alukard111

2021-07-08 23:43 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-10 15:42 UTC, SinimaWath requested changes

2021-07-10 15:42 UTC, SinimaWath commented on 4-module/3-task/index.js
> +
Тут проще забрать по index-у.

А то вот такую конструкцию сложно понять: `lastElementChild.previousElementSibling`

2021-07-10 15:42 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    Number(age) < 18 ? rowTr.style.textDecoration = 'line-through' : undefined
Тернарные операторы не предназначены, для случаев, когда нужно по условию выполнить операции.

Иначе тебе приходиться костылить:  `: undefined`.

Давай используем простой if

2021-07-10 18:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-11 10:32 UTC, SinimaWath approved these changes

2021-07-11 10:33 UTC, merged