Complited 5-module
js-tasks-ru/jsbasic-20210621_qb59egkw pull request #8
Opened 2021-07-13 15:16 UTC by alukard111

2021-07-13 15:17 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-13 21:21 UTC, SinimaWath requested changes

2021-07-13 21:21 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    hidden = !hidden
Давай попробуем без временной переменной hidden.

В div у тебя уже есть div.hidden

2021-07-14 08:48 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-15 16:47 UTC, SinimaWath approved these changes

2021-07-15 16:47 UTC, merged