6-module complited. It`s aliveee
js-tasks-ru/jsbasic-20210621_qb59egkw pull request #9
Opened 2021-07-22 23:37 UTC by alukard111

Влад, мне кажется я не совсем хорошо написал код. 
У меня возникали проблемы с вызовом someElement.offsetWidth, его просто не было т.к страница загружалась позже. И мне кажется код слиииишком длинный получился.

2021-07-22 23:39 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-23 13:19 UTC, SinimaWath requested changes

2021-07-23 13:19 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    this._cardElem.classList.add('card')
Там на первой строчке есть createElement, давай используем его ;) 
```
createElement(`
<div class="card">
  ${this._renderCard()}
</div>
`)
```

2021-07-23 13:19 UTC, SinimaWath commented on 6-module/3-task/index.js
> +      this._buttonProductAdd.map((element, index) => {
зачем тут map? Map нужен для преобразования массива. Давай forEach

2021-07-23 13:19 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    }
Тут много повторяющегося кода, давай переиспользуем, что получиться:
-       this._carouselSlider.style.transform = `translateX(-${this._carouselInnerWidth}px)`
-       this._maxSliderWith = this._carouselSlider.offsetWidth * (this.slides.length - 1)
-       this._checkingVisibilityArrows()

2021-07-23 13:19 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    this.elem = this._carousel
Будет  понятней и меньше кода, если сделаешь метод который возвращает елемент: `this.elem = this._render()`

2021-07-25 00:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-25 17:53 UTC, SinimaWath approved these changes

2021-07-25 17:53 UTC, merged